from .acp_user_actions import keyboard_markup
from .acp_user_actions import lang_markup
from .acp_user_actions import ban_markup
from .acp_user_actions import rights_markup
from .acp_user_actions import orders_a
from .acp_user_actions import order_info
from .ordering_kb import no_comm
from .ordering_kb import payment_type
from .ordering_kb import conf